os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
deploy:
  provider: script
  script:
  - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: OxgrBLpfjbM9mlglPUUlt3T5CUT13fHhonHSmb7UQKsnVykljKM8xnVTpiK4NDbg75JUJJzUMrDZUv8HqFV9u4aR6YX5C6yndU68PCnLrD9G2fxe9mBeQTeoW31p8NSEKCcC5AwLwAV2de23WR8oP0fYEw24sxNQ5KP03g/V+Bhdgyyj5JsOo/n2uavykZsrut0MuTUdLeiRmHTL0unNjsoNKZ7JUS/JIiOdOgD/11C0ehV3bK/srVmUMOkQccKexzIXY1fdABRkdDQjVc++Tt3hu0ovW9WH+PI3IKkQnpImjIVYIrfUlpoO3doDy/c5dfEGIhMsuvrdM0YVDOSCnDv0jRYe1HPqzc/4fSrnFOUIwnAz8LU9Ee1xuUzYcBQg2l05lhLXlmqecuiLcGHXwspdKoQYDGXsGrWHdG1AJ/fk7G5yt4+n5XV1jjbzpkaPQ3u1VjcJEZK46zqoIDVAWyK941nDASp5UKzBcJXlMZ6Gs3Mr/tCz8u1PK4SJg9pY/ohYZsX+0byVotm0YyJB/hMMP8QHfhYs8y5ywxQ9348sXRl9JQ9FJYjJ9OaTxOrM2Ly5W/9K78ILPt9XDerOqnOkvBlaYnbjakMWmr0N1WhLR02D4OaXvygoNbBY+1uUgToKyYYRw4xyqF+6XQlOPeT2dfoR6Ln/k0qS1ZpZGjg=
